apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: api
          imagePullPolicy: "Never"
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
            - name: DB
              value: "postgres://apiuser:apipass@postgres.default.svc.cluster.local:5432/apidb"